export enum RouteNames {
  Welcome = "Welcome",
  EnterEmail = "Enter-Email",
  EnterPassword = "Enter-Password",
  Demo = "Demo",
  Main = "Main",
  Home = "Home",
  Tips = "Tips",
  QR = "QR",
  QRModal = "QRModal",
  Stores = "Stores",
  Profile = "Profile",
  Register = "Register",
  RegisterInterests = "RegisterInterests",
  RegisterStack = "RegisterStack",
  RegisterOneLastStep = "RegisterOneLastStep",
  RegisterDone = "RegisterDone",
}
